version: "3"

services:
  redis:
    image: redis
    restart: always

  invest_analytics:
    restart: always
    build:
      context: ./invest_analytics
    ports:
      - "8000:8000"
    command: [ "python3", "./manage.py", "runserver", "0.0.0.0:8000" ]