# Generated by Django 4.0.5 on 2022-07-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_rename_iso_alpha2_country_iso_alpha_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_alpha_2',
            field=models.CharField(max_length=2, null=True, verbose_name='ISO Alpha 2'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_alpha_3',
            field=models.CharField(max_length=3, null=True, verbose_name='ISO Alpha 3'),
        ),
    ]
