# Generated by Django 4.0.5 on 2022-07-14 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_country_iso_alpha_2_alter_country_iso_alpha_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс')),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies_from', to='market.currency', verbose_name='Из валюты')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies_to', to='market.currency', verbose_name='В валюту')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
