# Generated by Django 4.0.5 on 2022-07-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_currency_type_currency_alter_currencycourse_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='abbreviation',
            field=models.CharField(max_length=10, unique=True, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='type_currency',
            field=models.CharField(choices=[('CURRENCY', 'Обычная валюта'), ('CRYPTOCURRENCY', 'Криптовалюта')], max_length=20, verbose_name='Тип валюты'),
        ),
    ]
