# Generated by Django 4.0.5 on 2022-07-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_currency_abbreviation_alter_currency_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencycourse',
            name='value',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20, verbose_name='Курс'),
        ),
    ]
