# Generated by Django 4.0.5 on 2022-07-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_country_iso_alpha2_country_iso_alpha3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='iso_alpha2',
            new_name='iso_alpha_2',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='iso_alpha3',
            new_name='iso_alpha_3',
        ),
        migrations.AddField(
            model_name='asset',
            name='last_price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Текущая цена'),
            preserve_default=False,
        ),
    ]
