# Generated by Django 4.0.5 on 2022-07-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_position_avg_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='commission',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='Комиссии'),
        ),
        migrations.AlterField(
            model_name='position',
            name='avg_price',
            field=models.DecimalField(decimal_places=6, max_digits=16, verbose_name='Средняя цена'),
        ),
    ]
