# Generated by Django 4.0.5 on 2022-07-16 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_currency_type_currency_alter_currencycourse_value'),
        ('app', '0004_position_commission_alter_position_avg_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='avg_price',
        ),
        migrations.AddField(
            model_name='position',
            name='avg_price_rub',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='Средняя цена RUB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='avg_price_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='Средняя цена USD'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CurrencyPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=16, verbose_name='Количество')),
                ('avg_price_rub', models.DecimalField(decimal_places=6, max_digits=16, verbose_name='Средняя цена в RUB')),
                ('avg_price_usd', models.DecimalField(decimal_places=6, max_digits=16, verbose_name='Средняя цена в USD')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_positions', to='app.account', verbose_name='Счет')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='market.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Валютная позиция',
                'verbose_name_plural': 'Валютные позиции',
            },
        ),
    ]
