# Generated by Django 4.0.5 on 2022-07-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounthistoricalmodel',
            options={'ordering': ['date'], 'verbose_name': 'Состояние', 'verbose_name_plural': 'Состояния'},
        ),
        migrations.AlterField(
            model_name='accounthistoricalmodel',
            name='total_profit',
            field=models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Общая прибыль'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Средняя цена'),
        ),
        migrations.AlterField(
            model_name='position',
            name='avg_price',
            field=models.DecimalField(decimal_places=6, max_digits=16, verbose_name='Средняя цена'),
        ),
    ]
