# Generated by Django 4.0.5 on 2022-07-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_accounthistoricalmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='avg_price',
            field=models.DecimalField(decimal_places=6, max_digits=16, verbose_name='Комиссии'),
        ),
    ]
